
import { NgModule } from '@angular/core';
import {ScrollDispatchModule} from '@angular/cdk/scrolling';

import { 
	MatButtonModule, 
	MatIconModule, 
	MatFormFieldModule, 
	MatInputModule,
	MatDatepickerModule,
	MatCheckboxModule,
	MatSidenavModule,
	MatToolbarModule,
	MatListModule,
	MatTabsModule,
	MatCardModule,
	MatSelectModule,
	MatProgressBarModule,
	MatRadioModule,
	MatDialogModule,
	MatStepperModule,
	MatTableModule,
	MatSortModule,
	MatPaginatorModule,
	MatSnackBarModule,
	MatProgressSpinnerModule,
	MatMenuModule,
	MatDividerModule,
	MatAutocompleteModule,
	MatGridListModule,
	MatExpansionModule,
	MatSlideToggleModule,
	MatButtonToggleModule,
	MatTooltipModule,
	MatSliderModule,
	MatBadgeModule,
	MatChipsModule
	
} from '@angular/material';
import { MatMomentDateModule } from '@angular/material-moment-adapter';

@NgModule({
	imports: [
		MatButtonModule, 
		MatIconModule, 
		MatFormFieldModule, 
		MatInputModule, 
		MatDatepickerModule,
		MatMomentDateModule,
		MatCheckboxModule,
		MatSidenavModule,
		MatToolbarModule,
		MatListModule,
		MatTabsModule,
		MatCardModule,
		MatSelectModule,
		MatProgressBarModule,
		MatRadioModule,
		MatDialogModule,
		MatStepperModule,
		MatTableModule,
		MatSortModule,
		MatPaginatorModule,
		MatSnackBarModule,
		MatProgressSpinnerModule,
		MatMenuModule,
		MatDividerModule,
		MatAutocompleteModule,
		MatGridListModule,
		MatExpansionModule,
		MatSlideToggleModule,
		MatButtonToggleModule,
		MatTooltipModule,
		MatSliderModule,
		MatBadgeModule,
		ScrollDispatchModule,
		MatChipsModule
	],
	exports: [
		MatButtonModule, 
		MatIconModule, 
		MatFormFieldModule, 
		MatInputModule, 
		MatDatepickerModule,
		MatMomentDateModule,
		MatCheckboxModule,
		MatSidenavModule,
		MatToolbarModule,
		MatListModule,
		MatTabsModule,
		MatCardModule,
		MatSelectModule,
		MatProgressBarModule,
		MatRadioModule,
		MatDialogModule,
		MatStepperModule,
		MatTableModule,
		MatSortModule,
		MatPaginatorModule,
		MatSnackBarModule,
		MatProgressSpinnerModule,
		MatMenuModule,
		MatDividerModule,
		MatAutocompleteModule,
		MatGridListModule,
		MatExpansionModule,
		MatSlideToggleModule,
		MatButtonToggleModule,
		MatTooltipModule,
		MatSliderModule,
		MatBadgeModule,
		ScrollDispatchModule,
		MatChipsModule
	]
})

export class MaterialModule{}